/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget_title;
    QWidget *main_page;
    QFrame *frame;
    QLabel *hisafe;
    QLabel *aaeon;
    QWidget *sub_page;
    QFrame *frame_2;
    QLabel *label_3;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout;
    QToolButton *sysBtn_1;
    QToolButton *hwmBtn_1;
    QToolButton *dioBtn_1;
    QToolButton *wdtBtn_1;
    QToolButton *fanBtn_1;
    QToolButton *busBtn_1;
    QToolButton *lightBtn_1;
    QStackedWidget *stackedWidget_context;
    QWidget *page_main;
    QToolButton *sysBtn;
    QToolButton *hwmBtn;
    QToolButton *dioBtn;
    QToolButton *wdtBtn;
    QToolButton *fanBtn;
    QToolButton *busBtn;
    QToolButton *lightBtn;
    QWidget *page_sys;
    QLabel *label_10;
    QLabel *label_4;
    QLabel *label_8;
    QLabel *label_12;
    QLabel *label_2;
    QLabel *sysImg;
    QLabel *label_9;
    QFrame *line_4;
    QLabel *label_13;
    QLabel *sysLab;
    QLabel *label_14;
    QFrame *line_3;
    QLabel *label_7;
    QLabel *label_5;
    QFrame *line_2;
    QLabel *label_11;
    QLabel *label_6;
    QLabel *label_15;
    QFrame *line;
    QLabel *label;
    QWidget *page_hwm;
    QFrame *line_15;
    QLabel *label_49;
    QFrame *line_16;
    QLabel *label_56;
    QLabel *hwmImg;
    QLabel *label_55;
    QFrame *line_14;
    QLabel *label_45;
    QLabel *hwmLab;
    QLabel *label_44;
    QLabel *label_46;
    QLabel *label_48;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_47;
    QLabel *label_51;
    QLabel *label_57;
    QLabel *label_50;
    QLabel *label_52;
    QLabel *label_60;
    QLabel *label_53;
    QLabel *label_61;
    QLabel *label_54;
    QLabel *label_62;
    QWidget *page_dio;
    QLabel *label_63;
    QLabel *dioImg;
    QLabel *dioLab;
    QFrame *line_13;
    QTableWidget *tableWidget;
    QPushButton *dio_setBtn;
    QWidget *page_wdt;
    QLabel *label_64;
    QFrame *line_17;
    QLabel *wdtImg;
    QLabel *hwmLab_2;
    QLabel *timerImg;
    QLabel *label_16;
    QRadioButton *secBtn;
    QRadioButton *minBtn;
    QLabel *label_17;
    QLabel *label_18;
    QPushButton *wdt_setBtn;
    QPushButton *wdt_clearBtn;
    QLabel *label_19;
    QComboBox *comboBox_5;
    QComboBox *comboBox_7;
    QCheckBox *checkBox;
    QWidget *page_fan;
    QFrame *line_18;
    QLabel *fanLab;
    QLabel *label_65;
    QLabel *fanImg;
    QLabel *label_66;
    QSlider *fanSlider;
    QComboBox *comboBox;
    QRadioButton *autoBtn;
    QRadioButton *manBtn;
    QLabel *label_67;
    QFrame *line_19;
    QLabel *label_68;
    QLabel *label_69;
    QLabel *label_70;
    QLabel *label_71;
    QLabel *label_72;
    QFrame *line_20;
    QLabel *label_73;
    QLabel *label_74;
    QLabel *label_75;
    QFrame *line_21;
    QLabel *label_76;
    QSpinBox *fanSpin;
    QWidget *page_bus;
    QLabel *busLab;
    QLabel *label_77;
    QFrame *line_22;
    QLabel *busImg;
    QLabel *label_78;
    QRadioButton *rbBtn;
    QRadioButton *rwBtn;
    QRadioButton *wwBtn;
    QRadioButton *wbBtn;
    QLabel *label_79;
    QComboBox *comboBox_2;
    QComboBox *comboBox_3;
    QLabel *label_80;
    QComboBox *comboBox_4;
    QLabel *label_82;
    QLabel *label_81;
    QComboBox *comboBox_6;
    QLabel *label_83;
    QLabel *label_20;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QLabel *label_21;
    QWidget *page_light;
    QLabel *lightLab;
    QLabel *label_84;
    QFrame *line_23;
    QLabel *lightImg;
    QLabel *label_85;
    QLabel *timerImg_2;
    QSlider *lightSlider_1;
    QLabel *label_86;
    QSlider *lightSlider_2;
    QLabel *label_87;
    QSlider *lightSlider_3;
    QSpinBox *lightSpin_1;
    QSpinBox *lightSpin_3;
    QSpinBox *lightSpin_2;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(1500, 900);
        MainWindow->setStyleSheet(QString::fromUtf8("#MainWindow{border-image: url(:/myImage/image/background.png);}\n"
"\n"
""));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        stackedWidget_title = new QStackedWidget(centralwidget);
        stackedWidget_title->setObjectName("stackedWidget_title");
        stackedWidget_title->setGeometry(QRect(10, 0, 1480, 90));
        stackedWidget_title->setStyleSheet(QString::fromUtf8(""));
        main_page = new QWidget();
        main_page->setObjectName("main_page");
        frame = new QFrame(main_page);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(-11, 0, 1501, 90));
        frame->setStyleSheet(QString::fromUtf8("# frame{border: 0px;}"));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        frame->setLineWidth(1);
        hisafe = new QLabel(frame);
        hisafe->setObjectName("hisafe");
        hisafe->setGeometry(QRect(0, 0, 220, 90));
        hisafe->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/hisafe.png);"));
        aaeon = new QLabel(frame);
        aaeon->setObjectName("aaeon");
        aaeon->setGeometry(QRect(1260, 0, 220, 90));
        aaeon->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/aaeonlogo.png);"));
        stackedWidget_title->addWidget(main_page);
        sub_page = new QWidget();
        sub_page->setObjectName("sub_page");
        frame_2 = new QFrame(sub_page);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(-10, 0, 1501, 90));
        frame_2->setStyleSheet(QString::fromUtf8(""));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        label_3 = new QLabel(frame_2);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(0, 0, 241, 91));
        label_3->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/hisafe.png);"));
        layoutWidget = new QWidget(frame_2);
        layoutWidget->setObjectName("layoutWidget");
        layoutWidget->setGeometry(QRect(920, 10, 536, 96));
        horizontalLayout = new QHBoxLayout(layoutWidget);
        horizontalLayout->setObjectName("horizontalLayout");
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        sysBtn_1 = new QToolButton(layoutWidget);
        sysBtn_1->setObjectName("sysBtn_1");
        sysBtn_1->setMinimumSize(QSize(70, 70));
        sysBtn_1->setFocusPolicy(Qt::TabFocus);
        sysBtn_1->setStyleSheet(QString::fromUtf8(""));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/myImage/image/system.png"), QSize(), QIcon::Normal, QIcon::Off);
        sysBtn_1->setIcon(icon);
        sysBtn_1->setIconSize(QSize(70, 70));
        sysBtn_1->setAutoRaise(true);

        horizontalLayout->addWidget(sysBtn_1);

        hwmBtn_1 = new QToolButton(layoutWidget);
        hwmBtn_1->setObjectName("hwmBtn_1");
        hwmBtn_1->setMinimumSize(QSize(70, 70));
        hwmBtn_1->setStyleSheet(QString::fromUtf8(""));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/myImage/image/monitor.png"), QSize(), QIcon::Normal, QIcon::Off);
        hwmBtn_1->setIcon(icon1);
        hwmBtn_1->setIconSize(QSize(70, 70));
        hwmBtn_1->setAutoRaise(true);

        horizontalLayout->addWidget(hwmBtn_1);

        dioBtn_1 = new QToolButton(layoutWidget);
        dioBtn_1->setObjectName("dioBtn_1");
        dioBtn_1->setMinimumSize(QSize(70, 70));
        dioBtn_1->setStyleSheet(QString::fromUtf8(""));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/myImage/image/DIO.png"), QSize(), QIcon::Normal, QIcon::Off);
        dioBtn_1->setIcon(icon2);
        dioBtn_1->setIconSize(QSize(70, 70));
        dioBtn_1->setAutoRaise(true);

        horizontalLayout->addWidget(dioBtn_1);

        wdtBtn_1 = new QToolButton(layoutWidget);
        wdtBtn_1->setObjectName("wdtBtn_1");
        wdtBtn_1->setMinimumSize(QSize(70, 70));
        wdtBtn_1->setFocusPolicy(Qt::TabFocus);
        wdtBtn_1->setStyleSheet(QString::fromUtf8(""));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/myImage/image/WatchDog.png"), QSize(), QIcon::Normal, QIcon::Off);
        wdtBtn_1->setIcon(icon3);
        wdtBtn_1->setIconSize(QSize(70, 70));
        wdtBtn_1->setAutoRaise(true);

        horizontalLayout->addWidget(wdtBtn_1);

        fanBtn_1 = new QToolButton(layoutWidget);
        fanBtn_1->setObjectName("fanBtn_1");
        fanBtn_1->setMinimumSize(QSize(70, 70));
        fanBtn_1->setFocusPolicy(Qt::TabFocus);
        fanBtn_1->setStyleSheet(QString::fromUtf8(""));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/myImage/image/fan.png"), QSize(), QIcon::Normal, QIcon::Off);
        fanBtn_1->setIcon(icon4);
        fanBtn_1->setIconSize(QSize(70, 70));
        fanBtn_1->setAutoRaise(true);

        horizontalLayout->addWidget(fanBtn_1);

        busBtn_1 = new QToolButton(layoutWidget);
        busBtn_1->setObjectName("busBtn_1");
        busBtn_1->setMinimumSize(QSize(70, 70));
        busBtn_1->setFocusPolicy(Qt::TabFocus);
        busBtn_1->setStyleSheet(QString::fromUtf8(""));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/myImage/image/Smbus.png"), QSize(), QIcon::Normal, QIcon::Off);
        busBtn_1->setIcon(icon5);
        busBtn_1->setIconSize(QSize(70, 70));
        busBtn_1->setAutoRaise(true);

        horizontalLayout->addWidget(busBtn_1);

        lightBtn_1 = new QToolButton(layoutWidget);
        lightBtn_1->setObjectName("lightBtn_1");
        lightBtn_1->setMinimumSize(QSize(70, 70));
        lightBtn_1->setFocusPolicy(Qt::TabFocus);
        lightBtn_1->setStyleSheet(QString::fromUtf8(""));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/myImage/image/backlightnew.png"), QSize(), QIcon::Normal, QIcon::Off);
        lightBtn_1->setIcon(icon6);
        lightBtn_1->setIconSize(QSize(70, 70));
        lightBtn_1->setAutoRaise(true);

        horizontalLayout->addWidget(lightBtn_1);

        stackedWidget_title->addWidget(sub_page);
        stackedWidget_context = new QStackedWidget(centralwidget);
        stackedWidget_context->setObjectName("stackedWidget_context");
        stackedWidget_context->setGeometry(QRect(10, 100, 1480, 750));
        stackedWidget_context->setStyleSheet(QString::fromUtf8(""));
        page_main = new QWidget();
        page_main->setObjectName("page_main");
        sysBtn = new QToolButton(page_main);
        sysBtn->setObjectName("sysBtn");
        sysBtn->setGeometry(QRect(291, 231, 180, 120));
        QFont font;
        font.setPointSize(14);
        sysBtn->setFont(font);
        sysBtn->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        sysBtn->setIcon(icon);
        sysBtn->setIconSize(QSize(80, 80));
        sysBtn->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        sysBtn->setAutoRaise(true);
        hwmBtn = new QToolButton(page_main);
        hwmBtn->setObjectName("hwmBtn");
        hwmBtn->setGeometry(QRect(562, 231, 120, 120));
        hwmBtn->setFont(font);
        hwmBtn->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        hwmBtn->setIcon(icon1);
        hwmBtn->setIconSize(QSize(80, 80));
        hwmBtn->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        hwmBtn->setAutoRaise(true);
        dioBtn = new QToolButton(page_main);
        dioBtn->setObjectName("dioBtn");
        dioBtn->setGeometry(QRect(783, 231, 120, 120));
        dioBtn->setFont(font);
        dioBtn->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        dioBtn->setIcon(icon2);
        dioBtn->setIconSize(QSize(80, 80));
        dioBtn->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        dioBtn->setAutoRaise(true);
        wdtBtn = new QToolButton(page_main);
        wdtBtn->setObjectName("wdtBtn");
        wdtBtn->setGeometry(QRect(1004, 231, 120, 120));
        wdtBtn->setFont(font);
        wdtBtn->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        wdtBtn->setIcon(icon3);
        wdtBtn->setIconSize(QSize(80, 80));
        wdtBtn->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        wdtBtn->setAutoRaise(true);
        fanBtn = new QToolButton(page_main);
        fanBtn->setObjectName("fanBtn");
        fanBtn->setGeometry(QRect(450, 450, 120, 120));
        fanBtn->setFont(font);
        fanBtn->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        fanBtn->setIcon(icon4);
        fanBtn->setIconSize(QSize(80, 80));
        fanBtn->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        fanBtn->setAutoRaise(true);
        busBtn = new QToolButton(page_main);
        busBtn->setObjectName("busBtn");
        busBtn->setGeometry(QRect(670, 450, 120, 120));
        busBtn->setFont(font);
        busBtn->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        busBtn->setIcon(icon5);
        busBtn->setIconSize(QSize(80, 80));
        busBtn->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        busBtn->setAutoRaise(true);
        lightBtn = new QToolButton(page_main);
        lightBtn->setObjectName("lightBtn");
        lightBtn->setGeometry(QRect(870, 450, 180, 120));
        lightBtn->setFont(font);
        lightBtn->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        lightBtn->setIcon(icon6);
        lightBtn->setIconSize(QSize(80, 80));
        lightBtn->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        lightBtn->setAutoRaise(true);
        stackedWidget_context->addWidget(page_main);
        page_sys = new QWidget();
        page_sys->setObjectName("page_sys");
        label_10 = new QLabel(page_sys);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(30, 460, 111, 17));
        QFont font1;
        font1.setPointSize(12);
        label_10->setFont(font1);
        label_10->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_4 = new QLabel(page_sys);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(30, 190, 101, 17));
        label_4->setFont(font1);
        label_4->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_8 = new QLabel(page_sys);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(30, 400, 111, 17));
        label_8->setFont(font1);
        label_8->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_12 = new QLabel(page_sys);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(10, 530, 181, 31));
        QFont font2;
        font2.setPointSize(17);
        label_12->setFont(font2);
        label_12->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_2 = new QLabel(page_sys);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(30, 160, 67, 17));
        label_2->setFont(font1);
        label_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        sysImg = new QLabel(page_sys);
        sysImg->setObjectName("sysImg");
        sysImg->setGeometry(QRect(10, 0, 80, 80));
        sysImg->setMinimumSize(QSize(71, 71));
        sysImg->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/system.png);\n"
"border-radius: 10px;"));
        label_9 = new QLabel(page_sys);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(30, 430, 111, 17));
        label_9->setFont(font1);
        label_9->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line_4 = new QFrame(page_sys);
        line_4->setObjectName("line_4");
        line_4->setGeometry(QRect(200, 540, 1291, 20));
        line_4->setStyleSheet(QString::fromUtf8(""));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        label_13 = new QLabel(page_sys);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(30, 580, 111, 17));
        label_13->setFont(font1);
        label_13->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        sysLab = new QLabel(page_sys);
        sysLab->setObjectName("sysLab");
        sysLab->setGeometry(QRect(110, 0, 331, 80));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(36, 31, 49, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        sysLab->setPalette(palette);
        QFont font3;
        font3.setPointSize(20);
        sysLab->setFont(font3);
        sysLab->setScaledContents(false);
        label_14 = new QLabel(page_sys);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(30, 610, 111, 17));
        label_14->setFont(font1);
        label_14->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line_3 = new QFrame(page_sys);
        line_3->setObjectName("line_3");
        line_3->setGeometry(QRect(230, 360, 1261, 20));
        line_3->setStyleSheet(QString::fromUtf8(""));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        label_7 = new QLabel(page_sys);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(10, 350, 211, 31));
        label_7->setFont(font2);
        label_7->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_5 = new QLabel(page_sys);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(30, 280, 111, 17));
        label_5->setFont(font1);
        label_5->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line_2 = new QFrame(page_sys);
        line_2->setObjectName("line_2");
        line_2->setGeometry(QRect(220, 240, 1271, 20));
        line_2->setStyleSheet(QString::fromUtf8(""));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label_11 = new QLabel(page_sys);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(30, 490, 111, 17));
        label_11->setFont(font1);
        label_11->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_6 = new QLabel(page_sys);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(30, 310, 81, 17));
        label_6->setFont(font1);
        label_6->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_15 = new QLabel(page_sys);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(10, 230, 201, 31));
        label_15->setFont(font2);
        label_15->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line = new QFrame(page_sys);
        line->setObjectName("line");
        line->setGeometry(QRect(190, 120, 1301, 20));
        line->setStyleSheet(QString::fromUtf8(""));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label = new QLabel(page_sys);
        label->setObjectName("label");
        label->setGeometry(QRect(10, 110, 181, 31));
        label->setFont(font2);
        label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        stackedWidget_context->addWidget(page_sys);
        page_hwm = new QWidget();
        page_hwm->setObjectName("page_hwm");
        line_15 = new QFrame(page_hwm);
        line_15->setObjectName("line_15");
        line_15->setGeometry(QRect(100, 420, 1391, 20));
        line_15->setStyleSheet(QString::fromUtf8(""));
        line_15->setFrameShape(QFrame::HLine);
        line_15->setFrameShadow(QFrame::Sunken);
        label_49 = new QLabel(page_hwm);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(10, 110, 121, 31));
        label_49->setFont(font2);
        label_49->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line_16 = new QFrame(page_hwm);
        line_16->setObjectName("line_16");
        line_16->setGeometry(QRect(140, 120, 1351, 20));
        line_16->setStyleSheet(QString::fromUtf8(""));
        line_16->setFrameShape(QFrame::HLine);
        line_16->setFrameShadow(QFrame::Sunken);
        label_56 = new QLabel(page_hwm);
        label_56->setObjectName("label_56");
        label_56->setGeometry(QRect(30, 460, 71, 17));
        label_56->setFont(font1);
        label_56->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        hwmImg = new QLabel(page_hwm);
        hwmImg->setObjectName("hwmImg");
        hwmImg->setGeometry(QRect(10, 0, 80, 80));
        hwmImg->setMinimumSize(QSize(71, 71));
        hwmImg->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/monitor.png);\n"
"border-radius: 10px;"));
        label_55 = new QLabel(page_hwm);
        label_55->setObjectName("label_55");
        label_55->setGeometry(QRect(10, 260, 141, 31));
        label_55->setFont(font2);
        label_55->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line_14 = new QFrame(page_hwm);
        line_14->setObjectName("line_14");
        line_14->setGeometry(QRect(160, 270, 1331, 20));
        line_14->setStyleSheet(QString::fromUtf8(""));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        label_45 = new QLabel(page_hwm);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(30, 160, 67, 17));
        label_45->setFont(font1);
        label_45->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        hwmLab = new QLabel(page_hwm);
        hwmLab->setObjectName("hwmLab");
        hwmLab->setGeometry(QRect(110, 0, 331, 80));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        hwmLab->setPalette(palette1);
        hwmLab->setFont(font3);
        hwmLab->setScaledContents(false);
        label_44 = new QLabel(page_hwm);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(30, 490, 61, 17));
        label_44->setFont(font1);
        label_44->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_46 = new QLabel(page_hwm);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(30, 190, 101, 17));
        label_46->setFont(font1);
        label_46->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_48 = new QLabel(page_hwm);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(10, 410, 81, 31));
        label_48->setFont(font2);
        label_48->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_58 = new QLabel(page_hwm);
        label_58->setObjectName("label_58");
        label_58->setGeometry(QRect(30, 220, 101, 17));
        label_58->setFont(font1);
        label_58->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_59 = new QLabel(page_hwm);
        label_59->setObjectName("label_59");
        label_59->setGeometry(QRect(30, 370, 101, 17));
        label_59->setFont(font1);
        label_59->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_47 = new QLabel(page_hwm);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(30, 310, 67, 17));
        label_47->setFont(font1);
        label_47->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_51 = new QLabel(page_hwm);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(30, 340, 101, 17));
        label_51->setFont(font1);
        label_51->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_57 = new QLabel(page_hwm);
        label_57->setObjectName("label_57");
        label_57->setGeometry(QRect(30, 520, 71, 17));
        label_57->setFont(font1);
        label_57->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_50 = new QLabel(page_hwm);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(30, 550, 61, 17));
        label_50->setFont(font1);
        label_50->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_52 = new QLabel(page_hwm);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(30, 610, 61, 17));
        label_52->setFont(font1);
        label_52->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_60 = new QLabel(page_hwm);
        label_60->setObjectName("label_60");
        label_60->setGeometry(QRect(30, 580, 71, 17));
        label_60->setFont(font1);
        label_60->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_53 = new QLabel(page_hwm);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(30, 640, 61, 17));
        label_53->setFont(font1);
        label_53->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_61 = new QLabel(page_hwm);
        label_61->setObjectName("label_61");
        label_61->setGeometry(QRect(30, 670, 71, 17));
        label_61->setFont(font1);
        label_61->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_54 = new QLabel(page_hwm);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(30, 700, 61, 17));
        label_54->setFont(font1);
        label_54->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_62 = new QLabel(page_hwm);
        label_62->setObjectName("label_62");
        label_62->setGeometry(QRect(30, 730, 61, 17));
        label_62->setFont(font1);
        label_62->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        stackedWidget_context->addWidget(page_hwm);
        page_dio = new QWidget();
        page_dio->setObjectName("page_dio");
        label_63 = new QLabel(page_dio);
        label_63->setObjectName("label_63");
        label_63->setGeometry(QRect(10, 110, 151, 31));
        label_63->setFont(font2);
        label_63->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        dioImg = new QLabel(page_dio);
        dioImg->setObjectName("dioImg");
        dioImg->setGeometry(QRect(10, 0, 80, 80));
        dioImg->setMinimumSize(QSize(71, 71));
        dioImg->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/DIO.png);\n"
"border-radius: 10px;"));
        dioLab = new QLabel(page_dio);
        dioLab->setObjectName("dioLab");
        dioLab->setGeometry(QRect(110, 0, 331, 80));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        dioLab->setPalette(palette2);
        dioLab->setFont(font3);
        dioLab->setScaledContents(false);
        line_13 = new QFrame(page_dio);
        line_13->setObjectName("line_13");
        line_13->setGeometry(QRect(170, 120, 1321, 20));
        line_13->setStyleSheet(QString::fromUtf8(""));
        line_13->setFrameShape(QFrame::HLine);
        line_13->setFrameShadow(QFrame::Sunken);
        tableWidget = new QTableWidget(page_dio);
        if (tableWidget->columnCount() < 4)
            tableWidget->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        if (tableWidget->rowCount() < 8)
            tableWidget->setRowCount(8);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(0, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(1, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(2, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(3, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(4, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(5, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(6, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(7, __qtablewidgetitem11);
        tableWidget->setObjectName("tableWidget");
        tableWidget->setGeometry(QRect(20, 160, 1261, 561));
        tableWidget->setLayoutDirection(Qt::LeftToRight);
        tableWidget->setStyleSheet(QString::fromUtf8("background-color: rgb(161, 175, 201);"));
        dio_setBtn = new QPushButton(page_dio);
        dio_setBtn->setObjectName("dio_setBtn");
        dio_setBtn->setGeometry(QRect(1350, 680, 101, 41));
        dio_setBtn->setStyleSheet(QString::fromUtf8(""));
        QIcon icon7;
        QString iconThemeName = QString::fromUtf8("go-next");
        if (QIcon::hasThemeIcon(iconThemeName)) {
            icon7 = QIcon::fromTheme(iconThemeName);
        } else {
            icon7.addFile(QString::fromUtf8("."), QSize(), QIcon::Normal, QIcon::Off);
        }
        dio_setBtn->setIcon(icon7);
        stackedWidget_context->addWidget(page_dio);
        page_wdt = new QWidget();
        page_wdt->setObjectName("page_wdt");
        label_64 = new QLabel(page_wdt);
        label_64->setObjectName("label_64");
        label_64->setGeometry(QRect(10, 110, 181, 31));
        label_64->setFont(font2);
        label_64->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line_17 = new QFrame(page_wdt);
        line_17->setObjectName("line_17");
        line_17->setGeometry(QRect(200, 120, 1291, 20));
        line_17->setStyleSheet(QString::fromUtf8(""));
        line_17->setFrameShape(QFrame::HLine);
        line_17->setFrameShadow(QFrame::Sunken);
        wdtImg = new QLabel(page_wdt);
        wdtImg->setObjectName("wdtImg");
        wdtImg->setGeometry(QRect(10, 0, 80, 80));
        wdtImg->setMinimumSize(QSize(71, 71));
        wdtImg->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/WatchDog.png);\n"
"border-radius: 10px;"));
        hwmLab_2 = new QLabel(page_wdt);
        hwmLab_2->setObjectName("hwmLab_2");
        hwmLab_2->setGeometry(QRect(110, 0, 331, 80));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        hwmLab_2->setPalette(palette3);
        hwmLab_2->setFont(font3);
        hwmLab_2->setScaledContents(false);
        timerImg = new QLabel(page_wdt);
        timerImg->setObjectName("timerImg");
        timerImg->setGeometry(QRect(80, 240, 231, 231));
        timerImg->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/timer(1).png);"));
        label_16 = new QLabel(page_wdt);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(420, 190, 111, 21));
        label_16->setFont(font);
        label_16->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        secBtn = new QRadioButton(page_wdt);
        secBtn->setObjectName("secBtn");
        secBtn->setGeometry(QRect(450, 240, 112, 23));
        secBtn->setFont(font1);
        secBtn->setStyleSheet(QString::fromUtf8(""));
        minBtn = new QRadioButton(page_wdt);
        minBtn->setObjectName("minBtn");
        minBtn->setGeometry(QRect(630, 240, 112, 23));
        minBtn->setFont(font1);
        minBtn->setStyleSheet(QString::fromUtf8(""));
        label_17 = new QLabel(page_wdt);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(420, 290, 151, 21));
        label_17->setFont(font);
        label_17->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_18 = new QLabel(page_wdt);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(420, 410, 151, 21));
        label_18->setFont(font);
        label_18->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        wdt_setBtn = new QPushButton(page_wdt);
        wdt_setBtn->setObjectName("wdt_setBtn");
        wdt_setBtn->setGeometry(QRect(1130, 640, 91, 41));
        wdt_setBtn->setStyleSheet(QString::fromUtf8(""));
        wdt_setBtn->setIcon(icon7);
        wdt_clearBtn = new QPushButton(page_wdt);
        wdt_clearBtn->setObjectName("wdt_clearBtn");
        wdt_clearBtn->setGeometry(QRect(1250, 640, 91, 41));
        wdt_clearBtn->setStyleSheet(QString::fromUtf8(""));
        QIcon icon8;
        iconThemeName = QString::fromUtf8("application-exit");
        if (QIcon::hasThemeIcon(iconThemeName)) {
            icon8 = QIcon::fromTheme(iconThemeName);
        } else {
            icon8.addFile(QString::fromUtf8("."), QSize(), QIcon::Normal, QIcon::Off);
        }
        wdt_clearBtn->setIcon(icon8);
        label_19 = new QLabel(page_wdt);
        label_19->setObjectName("label_19");
        label_19->setEnabled(true);
        label_19->setGeometry(QRect(980, 550, 361, 51));
        label_19->setStyleSheet(QString::fromUtf8("background-color: rgb(153, 193, 241);\n"
"color: rgb(28, 113, 216);\n"
"border-radius: 5px;"));
        label_19->setAlignment(Qt::AlignCenter);
        comboBox_5 = new QComboBox(page_wdt);
        comboBox_5->setObjectName("comboBox_5");
        comboBox_5->setGeometry(QRect(460, 340, 291, 41));
        comboBox_7 = new QComboBox(page_wdt);
        comboBox_7->setObjectName("comboBox_7");
        comboBox_7->setGeometry(QRect(510, 460, 241, 41));
        checkBox = new QCheckBox(page_wdt);
        checkBox->setObjectName("checkBox");
        checkBox->setGeometry(QRect(460, 460, 51, 41));
        checkBox->setLayoutDirection(Qt::LeftToRight);
        checkBox->setAutoFillBackground(false);
        checkBox->setStyleSheet(QString::fromUtf8("background-color: rgb(192, 191, 188);\n"
"color: rgb(224, 27, 36);\n"
"padding-left: 18px;"));
        checkBox->setIconSize(QSize(32, 32));
        checkBox->setCheckable(true);
        checkBox->setTristate(false);
        stackedWidget_context->addWidget(page_wdt);
        page_fan = new QWidget();
        page_fan->setObjectName("page_fan");
        line_18 = new QFrame(page_fan);
        line_18->setObjectName("line_18");
        line_18->setGeometry(QRect(180, 120, 1311, 20));
        line_18->setStyleSheet(QString::fromUtf8(""));
        line_18->setFrameShape(QFrame::HLine);
        line_18->setFrameShadow(QFrame::Sunken);
        fanLab = new QLabel(page_fan);
        fanLab->setObjectName("fanLab");
        fanLab->setGeometry(QRect(110, 0, 331, 80));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        fanLab->setPalette(palette4);
        fanLab->setFont(font3);
        fanLab->setScaledContents(false);
        label_65 = new QLabel(page_fan);
        label_65->setObjectName("label_65");
        label_65->setGeometry(QRect(10, 110, 161, 31));
        label_65->setFont(font2);
        label_65->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        fanImg = new QLabel(page_fan);
        fanImg->setObjectName("fanImg");
        fanImg->setGeometry(QRect(10, 0, 80, 80));
        fanImg->setMinimumSize(QSize(71, 71));
        fanImg->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/fan.png);\n"
"border-radius: 10px;"));
        label_66 = new QLabel(page_fan);
        label_66->setObjectName("label_66");
        label_66->setGeometry(QRect(20, 160, 91, 21));
        label_66->setFont(font1);
        label_66->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        fanSlider = new QSlider(page_fan);
        fanSlider->setObjectName("fanSlider");
        fanSlider->setGeometry(QRect(30, 720, 501, 16));
        fanSlider->setMaximum(100);
        fanSlider->setOrientation(Qt::Horizontal);
        comboBox = new QComboBox(page_fan);
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->setObjectName("comboBox");
        comboBox->setGeometry(QRect(30, 200, 231, 41));
        comboBox->setStyleSheet(QString::fromUtf8(""));
        autoBtn = new QRadioButton(page_fan);
        autoBtn->setObjectName("autoBtn");
        autoBtn->setGeometry(QRect(300, 210, 112, 23));
        autoBtn->setFont(font1);
        autoBtn->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 0, 0);\n"
""));
        manBtn = new QRadioButton(page_fan);
        manBtn->setObjectName("manBtn");
        manBtn->setGeometry(QRect(450, 210, 112, 23));
        manBtn->setFont(font1);
        manBtn->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 0, 0);"));
        label_67 = new QLabel(page_fan);
        label_67->setObjectName("label_67");
        label_67->setGeometry(QRect(10, 270, 111, 31));
        label_67->setFont(font2);
        label_67->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line_19 = new QFrame(page_fan);
        line_19->setObjectName("line_19");
        line_19->setGeometry(QRect(130, 280, 1361, 20));
        line_19->setStyleSheet(QString::fromUtf8(""));
        line_19->setFrameShape(QFrame::HLine);
        line_19->setFrameShadow(QFrame::Sunken);
        label_68 = new QLabel(page_fan);
        label_68->setObjectName("label_68");
        label_68->setGeometry(QRect(20, 320, 51, 21));
        label_68->setFont(font1);
        label_68->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_69 = new QLabel(page_fan);
        label_69->setObjectName("label_69");
        label_69->setGeometry(QRect(20, 360, 71, 21));
        label_69->setFont(font1);
        label_69->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_70 = new QLabel(page_fan);
        label_70->setObjectName("label_70");
        label_70->setGeometry(QRect(20, 400, 71, 21));
        label_70->setFont(font1);
        label_70->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_71 = new QLabel(page_fan);
        label_71->setObjectName("label_71");
        label_71->setGeometry(QRect(20, 540, 71, 21));
        label_71->setFont(font1);
        label_71->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_72 = new QLabel(page_fan);
        label_72->setObjectName("label_72");
        label_72->setGeometry(QRect(10, 450, 151, 31));
        label_72->setFont(font2);
        label_72->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line_20 = new QFrame(page_fan);
        line_20->setObjectName("line_20");
        line_20->setGeometry(QRect(160, 460, 1331, 20));
        line_20->setStyleSheet(QString::fromUtf8(""));
        line_20->setFrameShape(QFrame::HLine);
        line_20->setFrameShadow(QFrame::Sunken);
        label_73 = new QLabel(page_fan);
        label_73->setObjectName("label_73");
        label_73->setGeometry(QRect(20, 500, 51, 21));
        label_73->setFont(font1);
        label_73->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_74 = new QLabel(page_fan);
        label_74->setObjectName("label_74");
        label_74->setGeometry(QRect(20, 580, 71, 21));
        label_74->setFont(font1);
        label_74->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_75 = new QLabel(page_fan);
        label_75->setObjectName("label_75");
        label_75->setGeometry(QRect(10, 630, 191, 31));
        label_75->setFont(font2);
        label_75->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line_21 = new QFrame(page_fan);
        line_21->setObjectName("line_21");
        line_21->setGeometry(QRect(210, 640, 1281, 20));
        line_21->setStyleSheet(QString::fromUtf8(""));
        line_21->setFrameShape(QFrame::HLine);
        line_21->setFrameShadow(QFrame::Sunken);
        label_76 = new QLabel(page_fan);
        label_76->setObjectName("label_76");
        label_76->setGeometry(QRect(20, 680, 151, 21));
        label_76->setFont(font1);
        label_76->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        fanSpin = new QSpinBox(page_fan);
        fanSpin->setObjectName("fanSpin");
        fanSpin->setGeometry(QRect(550, 710, 61, 31));
        fanSpin->setStyleSheet(QString::fromUtf8("color: rgb(154, 153, 150);"));
        fanSpin->setMaximum(100);
        stackedWidget_context->addWidget(page_fan);
        page_bus = new QWidget();
        page_bus->setObjectName("page_bus");
        busLab = new QLabel(page_bus);
        busLab->setObjectName("busLab");
        busLab->setGeometry(QRect(110, 0, 331, 80));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        busLab->setPalette(palette5);
        busLab->setFont(font3);
        busLab->setScaledContents(false);
        label_77 = new QLabel(page_bus);
        label_77->setObjectName("label_77");
        label_77->setGeometry(QRect(10, 110, 161, 31));
        label_77->setFont(font2);
        label_77->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line_22 = new QFrame(page_bus);
        line_22->setObjectName("line_22");
        line_22->setGeometry(QRect(180, 120, 1311, 20));
        line_22->setStyleSheet(QString::fromUtf8(""));
        line_22->setFrameShape(QFrame::HLine);
        line_22->setFrameShadow(QFrame::Sunken);
        busImg = new QLabel(page_bus);
        busImg->setObjectName("busImg");
        busImg->setGeometry(QRect(10, 0, 80, 80));
        busImg->setMinimumSize(QSize(71, 71));
        busImg->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/Smbus.png);\n"
"border-radius: 10px;"));
        label_78 = new QLabel(page_bus);
        label_78->setObjectName("label_78");
        label_78->setGeometry(QRect(20, 160, 151, 21));
        label_78->setFont(font1);
        label_78->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        rbBtn = new QRadioButton(page_bus);
        rbBtn->setObjectName("rbBtn");
        rbBtn->setGeometry(QRect(30, 200, 112, 23));
        rbBtn->setStyleSheet(QString::fromUtf8(""));
        rwBtn = new QRadioButton(page_bus);
        rwBtn->setObjectName("rwBtn");
        rwBtn->setGeometry(QRect(170, 200, 112, 23));
        rwBtn->setStyleSheet(QString::fromUtf8(""));
        wwBtn = new QRadioButton(page_bus);
        wwBtn->setObjectName("wwBtn");
        wwBtn->setGeometry(QRect(450, 200, 112, 23));
        wwBtn->setStyleSheet(QString::fromUtf8(""));
        wwBtn->setChecked(true);
        wbBtn = new QRadioButton(page_bus);
        wbBtn->setObjectName("wbBtn");
        wbBtn->setGeometry(QRect(310, 200, 112, 23));
        wbBtn->setStyleSheet(QString::fromUtf8(""));
        label_79 = new QLabel(page_bus);
        label_79->setObjectName("label_79");
        label_79->setGeometry(QRect(20, 260, 151, 21));
        label_79->setFont(font1);
        label_79->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        comboBox_2 = new QComboBox(page_bus);
        comboBox_2->setObjectName("comboBox_2");
        comboBox_2->setGeometry(QRect(30, 300, 381, 41));
        comboBox_3 = new QComboBox(page_bus);
        comboBox_3->setObjectName("comboBox_3");
        comboBox_3->setGeometry(QRect(110, 410, 301, 41));
        label_80 = new QLabel(page_bus);
        label_80->setObjectName("label_80");
        label_80->setGeometry(QRect(20, 370, 151, 21));
        label_80->setFont(font1);
        label_80->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        comboBox_4 = new QComboBox(page_bus);
        comboBox_4->setObjectName("comboBox_4");
        comboBox_4->setGeometry(QRect(510, 300, 381, 41));
        label_82 = new QLabel(page_bus);
        label_82->setObjectName("label_82");
        label_82->setGeometry(QRect(500, 260, 151, 21));
        label_82->setFont(font1);
        label_82->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_81 = new QLabel(page_bus);
        label_81->setObjectName("label_81");
        label_81->setGeometry(QRect(30, 410, 81, 41));
        label_81->setFont(font1);
        label_81->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(94, 92, 100);"));
        comboBox_6 = new QComboBox(page_bus);
        comboBox_6->setObjectName("comboBox_6");
        comboBox_6->setGeometry(QRect(590, 410, 301, 41));
        label_83 = new QLabel(page_bus);
        label_83->setObjectName("label_83");
        label_83->setGeometry(QRect(510, 410, 81, 41));
        label_83->setFont(font1);
        label_83->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(94, 92, 100);"));
        label_20 = new QLabel(page_bus);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(30, 520, 381, 51));
        label_20->setStyleSheet(QString::fromUtf8("background-color: rgb(153, 193, 241);\n"
"color: rgb(28, 113, 216);\n"
"border-radius: 5px;"));
        pushButton_4 = new QPushButton(page_bus);
        pushButton_4->setObjectName("pushButton_4");
        pushButton_4->setGeometry(QRect(930, 680, 101, 41));
        pushButton_4->setStyleSheet(QString::fromUtf8(""));
        QIcon icon9;
        iconThemeName = QString::fromUtf8("mail-mark-read");
        if (QIcon::hasThemeIcon(iconThemeName)) {
            icon9 = QIcon::fromTheme(iconThemeName);
        } else {
            icon9.addFile(QString::fromUtf8("."), QSize(), QIcon::Normal, QIcon::Off);
        }
        pushButton_4->setIcon(icon9);
        pushButton_5 = new QPushButton(page_bus);
        pushButton_5->setObjectName("pushButton_5");
        pushButton_5->setGeometry(QRect(1040, 680, 101, 41));
        pushButton_5->setStyleSheet(QString::fromUtf8(""));
        QIcon icon10;
        iconThemeName = QString::fromUtf8("accessories-text-editor");
        if (QIcon::hasThemeIcon(iconThemeName)) {
            icon10 = QIcon::fromTheme(iconThemeName);
        } else {
            icon10.addFile(QString::fromUtf8("."), QSize(), QIcon::Normal, QIcon::Off);
        }
        pushButton_5->setIcon(icon10);
        label_21 = new QLabel(page_bus);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(510, 520, 381, 51));
        label_21->setStyleSheet(QString::fromUtf8("background-color: rgb(246, 97, 81);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px;"));
        stackedWidget_context->addWidget(page_bus);
        page_light = new QWidget();
        page_light->setObjectName("page_light");
        lightLab = new QLabel(page_light);
        lightLab->setObjectName("lightLab");
        lightLab->setGeometry(QRect(110, 0, 331, 80));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        lightLab->setPalette(palette6);
        lightLab->setFont(font3);
        lightLab->setScaledContents(false);
        label_84 = new QLabel(page_light);
        label_84->setObjectName("label_84");
        label_84->setGeometry(QRect(10, 110, 181, 31));
        label_84->setFont(font2);
        label_84->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        line_23 = new QFrame(page_light);
        line_23->setObjectName("line_23");
        line_23->setGeometry(QRect(200, 120, 1291, 20));
        line_23->setStyleSheet(QString::fromUtf8(""));
        line_23->setFrameShape(QFrame::HLine);
        line_23->setFrameShadow(QFrame::Sunken);
        lightImg = new QLabel(page_light);
        lightImg->setObjectName("lightImg");
        lightImg->setGeometry(QRect(10, 0, 80, 80));
        lightImg->setMinimumSize(QSize(71, 71));
        lightImg->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/backlightnew.png);\n"
"border-radius: 10px;"));
        label_85 = new QLabel(page_light);
        label_85->setObjectName("label_85");
        label_85->setGeometry(QRect(510, 210, 151, 21));
        label_85->setFont(font1);
        label_85->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        timerImg_2 = new QLabel(page_light);
        timerImg_2->setObjectName("timerImg_2");
        timerImg_2->setGeometry(QRect(60, 280, 351, 231));
        timerImg_2->setStyleSheet(QString::fromUtf8("border-image: url(:/myImage/image/light.png);"));
        lightSlider_1 = new QSlider(page_light);
        lightSlider_1->setObjectName("lightSlider_1");
        lightSlider_1->setGeometry(QRect(520, 250, 601, 16));
        lightSlider_1->setMaximum(100);
        lightSlider_1->setOrientation(Qt::Horizontal);
        label_86 = new QLabel(page_light);
        label_86->setObjectName("label_86");
        label_86->setGeometry(QRect(510, 350, 151, 21));
        label_86->setFont(font1);
        label_86->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lightSlider_2 = new QSlider(page_light);
        lightSlider_2->setObjectName("lightSlider_2");
        lightSlider_2->setGeometry(QRect(520, 390, 601, 16));
        lightSlider_2->setMaximum(100);
        lightSlider_2->setOrientation(Qt::Horizontal);
        label_87 = new QLabel(page_light);
        label_87->setObjectName("label_87");
        label_87->setGeometry(QRect(510, 490, 151, 21));
        label_87->setFont(font1);
        label_87->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lightSlider_3 = new QSlider(page_light);
        lightSlider_3->setObjectName("lightSlider_3");
        lightSlider_3->setGeometry(QRect(520, 530, 601, 16));
        lightSlider_3->setMaximum(100);
        lightSlider_3->setOrientation(Qt::Horizontal);
        lightSpin_1 = new QSpinBox(page_light);
        lightSpin_1->setObjectName("lightSpin_1");
        lightSpin_1->setGeometry(QRect(1160, 240, 81, 41));
        lightSpin_1->setStyleSheet(QString::fromUtf8("color: rgb(154, 153, 150);"));
        lightSpin_1->setMaximum(100);
        lightSpin_3 = new QSpinBox(page_light);
        lightSpin_3->setObjectName("lightSpin_3");
        lightSpin_3->setGeometry(QRect(1160, 520, 81, 41));
        lightSpin_3->setStyleSheet(QString::fromUtf8("color: rgb(154, 153, 150);"));
        lightSpin_3->setMaximum(100);
        lightSpin_2 = new QSpinBox(page_light);
        lightSpin_2->setObjectName("lightSpin_2");
        lightSpin_2->setGeometry(QRect(1160, 380, 81, 41));
        lightSpin_2->setStyleSheet(QString::fromUtf8("color: rgb(154, 153, 150);"));
        lightSpin_2->setMaximum(100);
        stackedWidget_context->addWidget(page_light);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 1500, 22));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        hisafe->setText(QString());
        aaeon->setText(QString());
        label_3->setText(QString());
        sysBtn_1->setText(QString());
        hwmBtn_1->setText(QString());
        dioBtn_1->setText(QString());
        wdtBtn_1->setText(QString());
        fanBtn_1->setText(QString());
        busBtn_1->setText(QCoreApplication::translate("MainWindow", "...", nullptr));
        lightBtn_1->setText(QString());
        sysBtn->setText(QCoreApplication::translate("MainWindow", "System Information", nullptr));
        hwmBtn->setText(QCoreApplication::translate("MainWindow", "H/W Monitor", nullptr));
        dioBtn->setText(QCoreApplication::translate("MainWindow", "DIO", nullptr));
        wdtBtn->setText(QCoreApplication::translate("MainWindow", "Watchdog", nullptr));
        fanBtn->setText(QCoreApplication::translate("MainWindow", "Smart Fan", nullptr));
        busBtn->setText(QCoreApplication::translate("MainWindow", "Smbus", nullptr));
        lightBtn->setText(QCoreApplication::translate("MainWindow", "Backlight Controller", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Pixel :", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Data Width :", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "Device :", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "RAM Information", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Name :", nullptr));
        sysImg->setText(QString());
        label_9->setText(QCoreApplication::translate("MainWindow", "Resolution :", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "Type :", nullptr));
        sysLab->setText(QCoreApplication::translate("MainWindow", "System Information", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "Clock Speed :", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Display Information", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Model Name :", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Refresh Rate :", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Bound ID :", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "Model Information", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "CPU Information", nullptr));
        label_49->setText(QCoreApplication::translate("MainWindow", "Fan Speed", nullptr));
        label_56->setText(QCoreApplication::translate("MainWindow", "VCORE :", nullptr));
        hwmImg->setText(QString());
        label_55->setText(QCoreApplication::translate("MainWindow", "Temperature", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindow", "CPU :", nullptr));
        hwmLab->setText(QCoreApplication::translate("MainWindow", "Hardware Monitor", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindow", "VBAT :", nullptr));
        label_46->setText(QCoreApplication::translate("MainWindow", "System :", nullptr));
        label_48->setText(QCoreApplication::translate("MainWindow", "Voltage", nullptr));
        label_58->setText(QCoreApplication::translate("MainWindow", "Chipset :", nullptr));
        label_59->setText(QCoreApplication::translate("MainWindow", "Chipset :", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindow", "CPU :", nullptr));
        label_51->setText(QCoreApplication::translate("MainWindow", "System :", nullptr));
        label_57->setText(QCoreApplication::translate("MainWindow", "12V :", nullptr));
        label_50->setText(QCoreApplication::translate("MainWindow", "2V5 :", nullptr));
        label_52->setText(QCoreApplication::translate("MainWindow", "DIMM :", nullptr));
        label_60->setText(QCoreApplication::translate("MainWindow", "5V :", nullptr));
        label_53->setText(QCoreApplication::translate("MainWindow", "3V3 :", nullptr));
        label_61->setText(QCoreApplication::translate("MainWindow", "5V :", nullptr));
        label_54->setText(QCoreApplication::translate("MainWindow", "5VSB :", nullptr));
        label_62->setText(QCoreApplication::translate("MainWindow", "3VSB :", nullptr));
        label_63->setText(QCoreApplication::translate("MainWindow", "Digital IO List", nullptr));
        dioImg->setText(QString());
        dioLab->setText(QCoreApplication::translate("MainWindow", "Digital I/O", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("MainWindow", "Current Mode", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("MainWindow", "Current Value", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("MainWindow", "Setting Mode", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("MainWindow", "Setting Value", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget->verticalHeaderItem(0);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("MainWindow", "DIO1", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget->verticalHeaderItem(1);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("MainWindow", "DIO2", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget->verticalHeaderItem(2);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("MainWindow", "DIO3", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget->verticalHeaderItem(3);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("MainWindow", "DIO4", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget->verticalHeaderItem(4);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("MainWindow", "DIO5", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget->verticalHeaderItem(5);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("MainWindow", "DIO6", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget->verticalHeaderItem(6);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("MainWindow", "DIO7", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget->verticalHeaderItem(7);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("MainWindow", "DIO8", nullptr));
        dio_setBtn->setText(QCoreApplication::translate("MainWindow", " Set", nullptr));
        label_64->setText(QCoreApplication::translate("MainWindow", "WatchDog Timer", nullptr));
        wdtImg->setText(QString());
        hwmLab_2->setText(QCoreApplication::translate("MainWindow", "WatchDog", nullptr));
        timerImg->setText(QString());
        label_16->setText(QCoreApplication::translate("MainWindow", "Count Mode", nullptr));
        secBtn->setText(QCoreApplication::translate("MainWindow", "Second", nullptr));
        minBtn->setText(QCoreApplication::translate("MainWindow", "Minute", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "Countdown Time", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "Auto Reload", nullptr));
        wdt_setBtn->setText(QCoreApplication::translate("MainWindow", " Set", nullptr));
        wdt_clearBtn->setText(QCoreApplication::translate("MainWindow", " Clear", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "0 seconds remaining", nullptr));
        checkBox->setText(QString());
        fanLab->setText(QCoreApplication::translate("MainWindow", "Smart Fan", nullptr));
        label_65->setText(QCoreApplication::translate("MainWindow", "Monitored Fan", nullptr));
        fanImg->setText(QString());
        label_66->setText(QCoreApplication::translate("MainWindow", "Select Fan :", nullptr));
        comboBox->setItemText(0, QCoreApplication::translate("MainWindow", "Fan 0", nullptr));
        comboBox->setItemText(1, QCoreApplication::translate("MainWindow", "Fan 1", nullptr));

        autoBtn->setText(QCoreApplication::translate("MainWindow", "Auto", nullptr));
        manBtn->setText(QCoreApplication::translate("MainWindow", "Manual", nullptr));
        label_67->setText(QCoreApplication::translate("MainWindow", "Fan Speed", nullptr));
        label_68->setText(QCoreApplication::translate("MainWindow", "CPU :", nullptr));
        label_69->setText(QCoreApplication::translate("MainWindow", "Chipset :", nullptr));
        label_70->setText(QCoreApplication::translate("MainWindow", "System :", nullptr));
        label_71->setText(QCoreApplication::translate("MainWindow", "Chipset :", nullptr));
        label_72->setText(QCoreApplication::translate("MainWindow", "Temperature", nullptr));
        label_73->setText(QCoreApplication::translate("MainWindow", "CPU :", nullptr));
        label_74->setText(QCoreApplication::translate("MainWindow", "System :", nullptr));
        label_75->setText(QCoreApplication::translate("MainWindow", "Smart Fan Control", nullptr));
        label_76->setText(QCoreApplication::translate("MainWindow", "Manual Speed :", nullptr));
        busLab->setText(QCoreApplication::translate("MainWindow", "Smbus", nullptr));
        label_77->setText(QCoreApplication::translate("MainWindow", "Smbus Setting", nullptr));
        busImg->setText(QString());
        label_78->setText(QCoreApplication::translate("MainWindow", "Operation Options :", nullptr));
        rbBtn->setText(QCoreApplication::translate("MainWindow", "Read Byte", nullptr));
        rwBtn->setText(QCoreApplication::translate("MainWindow", "Read Word", nullptr));
        wwBtn->setText(QCoreApplication::translate("MainWindow", "Write Word", nullptr));
        wbBtn->setText(QCoreApplication::translate("MainWindow", "Write Byte", nullptr));
        label_79->setText(QCoreApplication::translate("MainWindow", "Device Address :", nullptr));
        comboBox_3->setCurrentText(QString());
        label_80->setText(QCoreApplication::translate("MainWindow", "Data to Write :", nullptr));
        label_82->setText(QCoreApplication::translate("MainWindow", "Register Offset :", nullptr));
        label_81->setText(QCoreApplication::translate("MainWindow", " Low Byte", nullptr));
        comboBox_6->setCurrentText(QString());
        label_83->setText(QCoreApplication::translate("MainWindow", " High Byte", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "   Received Data :", nullptr));
        pushButton_4->setText(QCoreApplication::translate("MainWindow", " Read", nullptr));
        pushButton_5->setText(QCoreApplication::translate("MainWindow", " Write", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "   Status :", nullptr));
        lightLab->setText(QCoreApplication::translate("MainWindow", "Backlight Controller", nullptr));
        label_84->setText(QCoreApplication::translate("MainWindow", "Backlight Setting", nullptr));
        lightImg->setText(QString());
        label_85->setText(QCoreApplication::translate("MainWindow", "Device 1 Brightness", nullptr));
        timerImg_2->setText(QString());
        label_86->setText(QCoreApplication::translate("MainWindow", "Device 2 Brightness", nullptr));
        label_87->setText(QCoreApplication::translate("MainWindow", "Device 3 Brightness", nullptr));
        lightSpin_1->setSuffix(QCoreApplication::translate("MainWindow", "%", nullptr));
        lightSpin_3->setSuffix(QCoreApplication::translate("MainWindow", "%", nullptr));
        lightSpin_2->setSuffix(QCoreApplication::translate("MainWindow", "%", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
